[package]
name = "crossprogress"
version = "0.1.0"
authors = ["JustinRlle <justin.rerolle@protonmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.14"
